[project]
name = "wild-llamas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "huggingface-hub>=0.32.4",
    "hydra-core>=1.3.2",
    "torch>=2.7.0",
    "transformers>=4.52.4",
]
