base_model: "meta-llama/Llama-3.1-8B-Instruct"

# based on https://arxiv.org/pdf/2505.05464#page=1.95
models:
  - "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
  - "EtashGuha/llama3-mammoth-dcft"
  - "TIGER-Lab/MAmmoTH2-8B"
  - "Magpie-Align/Llama-3-8B-Magpie-Align-SFT-v0.3"
  - "hkust-nlp/dart-math-llama3-8b-uniform"
  - "hkust-nlp/dart-math-llama3-8b-prop2diff"

hydra:
  run:
    dir: "outputs/hydra"

merge:
  method: weight_averaging_running

  task_arithmetic:
    scaling_factor: 1.0

  ties:
    scaling_factor: 1.0
    prune_percentile: 0.2